source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OutputTo_Example', :exclusive => true do
  pod "OutputTo", :path => "../"
end

target 'OutputTo_Tests', :exclusive => true do
  pod "OutputTo", :path => "../"

  pod 'Kiwi'
end
