source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!                           # KWHaveValueMatcher.m:45:47: warning: 'isEqualOrMatches:' is deprecated

target 'Tests', :exclusive => true do
  pod "OutputTo", :path => "../"
  pod 'Kiwi'
end
