# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.1
cache:
  - bundler
  - cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
script:
  - pod --version
  - pod lib lint --allow-warnings
  - xcodebuild test -workspace Example/OutputTo.xcworkspace -scheme Tests -sdk iphonesimulator
